/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_web_android_jni_Arithmetic */

#ifndef _Included_com_web_android_jni_Arithmetic
#define _Included_com_web_android_jni_Arithmetic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_web_android_jni_Arithmetic
 * Method:    add
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_web_android_jni_Arithmetic_add
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
